package com.hoabui.virtualbody3d.ui.theme.tokens.semantic

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import com.hoabui.virtualbody3d.ui.theme.tokens.primitive.PrimitiveAlphaTokens
import com.hoabui.virtualbody3d.ui.theme.tokens.primitive.PrimitiveColorTokens

/**
 * Semantic colors – Holistic Vitality. Light: sage primary / sand surfaces / slate text.
 * Dark: muted sage primary / deep moss surfaces / parchment text. Maps primitives to UI roles.
 */
@Immutable
data class SemanticColorTokens(
    val primary: Color,
    val primarySoft: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val background: Color,
    /** Same hue as [background] at [PrimitiveAlphaTokens.SUBTLE_LAYER] — vertical fade (e.g. top bar). */
    val backgroundSubtleGradientEnd: Color,
    val surface: Color,
    val surfaceElevated: Color,
    val surfaceSubtle: Color,
    val borderSubtle: Color,
    val borderStrong: Color,
    val textPrimary: Color,
    /** [textPrimary] at [PrimitiveAlphaTokens.SUBTLE_LAYER] — soft foreground icons. */
    val textPrimarySoft: Color,
    /** Accent (Terracotta) — badges, highlights; pairs with [onAccent]. */
    val accent: Color,
    val onAccent: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val textPlaceholder: Color,
    val textBlack: Color,
    val error: Color,
    val onPrimary: Color,
    val onError: Color,
    val info: Color,
    val onInfo: Color,
    val infoContainer: Color,
    val onInfoContainer: Color,
    val success: Color,
    val onSuccess: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val warning: Color,
    val onWarning: Color,
    val warningContainer: Color,
    val onWarningContainer: Color,
    val surfaceBorder: Color,
    val outlineSoft: Color,
    val surfaceOverlay: Color,
    val backgroundTransparent: Color,
    val backgroundScrim: Color,
    val previewTrack: Color,
    val primarySelected: Color,
    val dashboardPanelBackground: Color,
    val dashboardHandle: Color,
    val dashboardCalorieCardBackground: Color,
    val dashboardRingTrack: Color,
    val dashboardMealCardBackground: Color,
    val dashboardMealImageBackground: Color,
    val dashboardSummaryCardBackground: Color,
    val dashboardFloatingNavBackground: Color,
    val dashboardFloatingNavBorder: Color,
    val calorieDeficitPositive: Color,
    val calorieDeficitNegative: Color,
    val calorieRingTrack: Color,
    val calorieRingBackground: Color,
    val calorieIntake: Color,
    val calorieBurned: Color,
    val splashBackground: Color,
    val splashCardBackground: Color,
    /** Body region chip: Chest */
    val bodyRegionChest: Color,
    /** Body region chip: Back */
    val bodyRegionBack: Color,
    /** Body region chip: Shoulders */
    val bodyRegionShoulders: Color,
    /** Body region chip: Arms */
    val bodyRegionArms: Color,
    /** Body region chip: Core */
    val bodyRegionCore: Color,
    /** Body region chip: Legs */
    val bodyRegionLegs: Color,
    /** Bordered highlight around the exercise library weekly heatmap card (primary tint). */
    val exerciseLibraryHeatmapCardBorder: Color,
)

fun lightSemanticColors(primitive: PrimitiveColorTokens): SemanticColorTokens {
    return SemanticColorTokens(
        primary = primitive.primary,
        primarySoft = primitive.primaryContainerLight,
        onPrimaryContainer = primitive.onPrimaryContainerLight,
        secondary = primitive.secondary,
        onSecondary = primitive.onSecondary,
        secondaryContainer = primitive.secondaryContainerLight,
        onSecondaryContainer = primitive.onSecondaryContainerLight,
        background = primitive.backgroundLight,
        backgroundSubtleGradientEnd = primitive.backgroundLight.copy(alpha = PrimitiveAlphaTokens.SUBTLE_LAYER),
        surface = primitive.surfaceLight,
        surfaceElevated = primitive.surfaceLight,
        surfaceSubtle = primitive.surfaceVariantLight,
        borderSubtle = primitive.borderSubtleLight,
        borderStrong = primitive.outlineLight,
        textPrimary = primitive.textPrimaryLight,
        textPrimarySoft = primitive.textPrimaryLight.copy(alpha = PrimitiveAlphaTokens.SUBTLE_LAYER),
        accent = primitive.secondary,
        onAccent = primitive.onSecondary,
        textSecondary = primitive.textSecondaryLight,
        textMuted = primitive.textSecondaryLight,
        textPlaceholder = Color(0xFF757575),
        textBlack = Color(0xFF000000),
        error = primitive.error,
        onPrimary = primitive.onPrimary,
        onError = primitive.onPrimary,
        info = Color(0xFF1D4ED8),
        onInfo = Color(0xFFFFFFFF),
        infoContainer = Color(0xFFDBEAFE),
        onInfoContainer = Color(0xFF1E3A8A),
        success = Color(0xFF15803D),
        onSuccess = Color(0xFFFFFFFF),
        successContainer = Color(0xFFDCFCE7),
        onSuccessContainer = Color(0xFF14532D),
        warning = Color(0xFFD97706),
        onWarning = Color(0xFFFFFFFF),
        warningContainer = Color(0xFFFEF3C7),
        onWarningContainer = Color(0xFF78350F),
        surfaceBorder = primitive.borderSubtleLight,
        outlineSoft = primitive.outlineLight,
        surfaceOverlay = primitive.surfaceLight,
        backgroundTransparent = primitive.transparent,
        backgroundScrim = primitive.backgroundDark,
        previewTrack = primitive.borderSubtleLight,
        primarySelected = primitive.primaryContainerLight,
        dashboardPanelBackground = primitive.surfaceLight,
        dashboardHandle = primitive.outlineLight,
        dashboardCalorieCardBackground = primitive.surfaceLight,
        dashboardRingTrack = primitive.outlineLight,
        dashboardMealCardBackground = primitive.surfaceLight,
        dashboardMealImageBackground = primitive.surfaceVariantLight,
        dashboardSummaryCardBackground = primitive.surfaceLight,
        dashboardFloatingNavBackground = primitive.surfaceLight,
        dashboardFloatingNavBorder = primitive.borderSubtleLight,
        calorieDeficitPositive = Color(0xFF16A34A),
        calorieDeficitNegative = Color(0xFFDC2626),
        calorieRingTrack = primitive.borderSubtleLight,
        calorieRingBackground = primitive.outlineLight,
        calorieIntake = Color(0xFF3B82F6),
        calorieBurned = Color(0xFFFF4D6D),
        splashBackground = primitive.primary,
        splashCardBackground = primitive.splashCard,
        bodyRegionChest = Color(0xFFDC2626),
        bodyRegionBack = Color(0xFF2563EB),
        bodyRegionShoulders = Color(0xFFEA580C),
        bodyRegionArms = Color(0xFF7C3AED),
        bodyRegionCore = Color(0xFF059669),
        bodyRegionLegs = Color(0xFF0D9488),
        exerciseLibraryHeatmapCardBorder = primitive.primary.copy(alpha = PrimitiveAlphaTokens.MEDIUM),
    )
}

fun darkSemanticColors(primitive: PrimitiveColorTokens): SemanticColorTokens {
    return SemanticColorTokens(
        primary = primitive.primaryDark,
        primarySoft = primitive.primaryContainerDark,
        onPrimaryContainer = primitive.onPrimaryContainerDark,
        secondary = primitive.secondary,
        onSecondary = primitive.onSecondary,
        secondaryContainer = primitive.secondaryContainerDark,
        onSecondaryContainer = primitive.onSecondaryContainerDark,
        background = primitive.backgroundDark,
        backgroundSubtleGradientEnd = primitive.backgroundDark.copy(alpha = PrimitiveAlphaTokens.SUBTLE_LAYER),
        surface = primitive.surfaceDark,
        surfaceElevated = primitive.surfaceDark,
        surfaceSubtle = primitive.surfaceVariantDark,
        borderSubtle = primitive.borderSubtleDark,
        borderStrong = primitive.outlineDark,
        textPrimary = primitive.textPrimaryDark,
        textPrimarySoft = primitive.textPrimaryDark.copy(alpha = PrimitiveAlphaTokens.SUBTLE_LAYER),
        accent = primitive.secondary,
        onAccent = primitive.onSecondary,
        textSecondary = primitive.textSecondaryDark,
        textMuted = primitive.textSecondaryDark,
        textPlaceholder = Color(0xFF9CA8A4),
        textBlack = primitive.textPrimaryDark,
        error = primitive.error,
        onPrimary = primitive.onPrimary,
        onError = primitive.onPrimary,
        info = Color(0xFF93C5FD),
        onInfo = Color(0xFF0B1E4D),
        infoContainer = Color(0xFF1E3A8A),
        onInfoContainer = Color(0xFFDBEAFE),
        success = Color(0xFF86EFAC),
        onSuccess = Color(0xFF052E16),
        successContainer = Color(0xFF166534),
        onSuccessContainer = Color(0xFFDCFCE7),
        warning = Color(0xFFFCD34D),
        onWarning = Color(0xFF422006),
        warningContainer = Color(0xFF92400E),
        onWarningContainer = Color(0xFFFEF3C7),
        surfaceBorder = primitive.borderSubtleDark,
        outlineSoft = primitive.outlineDark,
        surfaceOverlay = primitive.surfaceDark,
        backgroundTransparent = primitive.transparent,
        backgroundScrim = primitive.backgroundDark,
        previewTrack = primitive.outlineDark,
        primarySelected = primitive.primaryContainerDark,
        dashboardPanelBackground = primitive.surfaceDark,
        dashboardHandle = primitive.outlineDark,
        dashboardCalorieCardBackground = primitive.surfaceDark,
        dashboardRingTrack = primitive.outlineDark,
        dashboardMealCardBackground = primitive.surfaceDark,
        dashboardMealImageBackground = primitive.surfaceVariantDark,
        dashboardSummaryCardBackground = primitive.surfaceDark,
        dashboardFloatingNavBackground = primitive.surfaceDark,
        dashboardFloatingNavBorder = primitive.borderSubtleDark,
        calorieDeficitPositive = Color(0xFF16A34A),
        calorieDeficitNegative = Color(0xFFDC2626),
        calorieRingTrack = primitive.borderSubtleDark,
        calorieRingBackground = primitive.outlineDark,
        calorieIntake = Color(0xFF60A5FA),
        calorieBurned = Color(0xFFFF758F),
        splashBackground = primitive.primaryDark,
        splashCardBackground = primitive.splashCard,
        bodyRegionChest = Color(0xFFDC2626),
        bodyRegionBack = Color(0xFF2563EB),
        bodyRegionShoulders = Color(0xFFEA580C),
        bodyRegionArms = Color(0xFF7C3AED),
        bodyRegionCore = Color(0xFF059669),
        bodyRegionLegs = Color(0xFF0D9488),
        exerciseLibraryHeatmapCardBorder = primitive.primaryDark.copy(alpha = PrimitiveAlphaTokens.MEDIUM),
    )
}
