package com.hoabui.virtualbody3d.ui.theme.tokens.semantic

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import com.hoabui.virtualbody3d.ui.theme.tokens.primitive.PrimitiveColorTokens

/**
 * Semantic colors – wine-plum brand. Maps primitive tokens to UI meaning.
 * Legacy names (surfaceBorder, outlineSoft, dashboard*, etc.) kept for compatibility.
 */
@Immutable
data class SemanticColorTokens(
    val primary: Color,
    val primarySoft: Color,
    val onPrimaryContainer: Color,
    val background: Color,
    val surface: Color,
    val surfaceElevated: Color,
    val surfaceSubtle: Color,
    val borderSubtle: Color,
    val borderStrong: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val textPlaceholder: Color,
    val textBlack: Color,
    val error: Color,
    val onPrimary: Color,
    val onError: Color,
    val surfaceBorder: Color,
    val outlineSoft: Color,
    val surfaceOverlay: Color,
    val backgroundTransparent: Color,
    val backgroundScrim: Color,
    val previewTrack: Color,
    val primarySelected: Color,
    val dashboardPanelBackground: Color,
    val dashboardHandle: Color,
    val dashboardNutritionCardBackground: Color,
    val dashboardNutritionCardBorder: Color,
    val dashboardRingTrack: Color,
    val dashboardMealCardBackground: Color,
    val dashboardMealImageBackground: Color,
    val dashboardSummaryCardBackground: Color,
    val dashboardFloatingNavBackground: Color,
    val dashboardFloatingNavBorder: Color,
    val calendarYearBackground: Color,
    val calendarSelectedBorder: Color,
    val splashBackground: Color,
    val splashCardBackground: Color
)

fun lightSemanticColors(primitive: PrimitiveColorTokens): SemanticColorTokens {
    return SemanticColorTokens(
        primary = primitive.primary,
        primarySoft = primitive.primaryContainerLight,
        onPrimaryContainer = primitive.onPrimaryContainerLight,
        background = primitive.backgroundLight,
        surface = primitive.surfaceLight,
        surfaceElevated = primitive.surfaceLight,
        surfaceSubtle = primitive.surfaceVariantLight,
        borderSubtle = primitive.borderSubtleLight,
        borderStrong = primitive.outlineLight,
        textPrimary = primitive.textPrimaryLight,
        textSecondary = primitive.textSecondaryLight,
        textMuted = primitive.textSecondaryLight,
        textPlaceholder = Color(0xFF757575),
        textBlack = Color(0xFF000000),
        error = primitive.error,
        onPrimary = primitive.onPrimary,
        onError = primitive.onPrimary,
        surfaceBorder = primitive.borderSubtleLight,
        outlineSoft = primitive.outlineLight,
        surfaceOverlay = primitive.surfaceLight,
        backgroundTransparent = primitive.transparent,
        backgroundScrim = primitive.backgroundDark,
        previewTrack = primitive.borderSubtleLight,
        primarySelected = primitive.primaryContainerLight,
        dashboardPanelBackground = primitive.surfaceLight,
        dashboardHandle = primitive.outlineLight,
        dashboardNutritionCardBackground = primitive.surfaceLight,
        dashboardNutritionCardBorder = primitive.borderSubtleLight,
        dashboardRingTrack = primitive.outlineLight,
        dashboardMealCardBackground = primitive.surfaceLight,
        dashboardMealImageBackground = primitive.surfaceVariantLight,
        dashboardSummaryCardBackground = primitive.surfaceLight,
        dashboardFloatingNavBackground = primitive.surfaceLight,
        dashboardFloatingNavBorder = primitive.borderSubtleLight,
        calendarYearBackground = primitive.primaryContainerLight,
        calendarSelectedBorder = primitive.primary,
        splashBackground = primitive.primary,
        splashCardBackground = primitive.splashCard
    )
}

fun darkSemanticColors(primitive: PrimitiveColorTokens): SemanticColorTokens {
    return SemanticColorTokens(
        primary = primitive.primary,
        primarySoft = primitive.primaryContainerDark,
        onPrimaryContainer = primitive.onPrimaryContainerDark,
        background = primitive.backgroundDark,
        surface = primitive.surfaceDark,
        surfaceElevated = primitive.surfaceDark,
        surfaceSubtle = primitive.surfaceVariantDark,
        borderSubtle = primitive.borderSubtleDark,
        borderStrong = primitive.outlineDark,
        textPrimary = primitive.textPrimaryDark,
        textSecondary = primitive.textSecondaryDark,
        textMuted = primitive.textSecondaryDark,
        textPlaceholder = Color(0xFFB0B0B0),
        textBlack = Color(0xFFFFFFFF),
        error = primitive.error,
        onPrimary = primitive.onPrimary,
        onError = primitive.onPrimary,
        surfaceBorder = primitive.borderSubtleDark,
        outlineSoft = primitive.outlineDark,
        surfaceOverlay = primitive.surfaceDark,
        backgroundTransparent = primitive.transparent,
        backgroundScrim = primitive.backgroundDark,
        previewTrack = primitive.outlineDark,
        primarySelected = primitive.primaryContainerDark,
        dashboardPanelBackground = primitive.surfaceDark,
        dashboardHandle = primitive.outlineDark,
        dashboardNutritionCardBackground = primitive.surfaceDark,
        dashboardNutritionCardBorder = primitive.borderSubtleDark,
        dashboardRingTrack = primitive.outlineDark,
        dashboardMealCardBackground = primitive.surfaceDark,
        dashboardMealImageBackground = primitive.surfaceVariantDark,
        dashboardSummaryCardBackground = primitive.surfaceDark,
        dashboardFloatingNavBackground = primitive.surfaceDark,
        dashboardFloatingNavBorder = primitive.borderSubtleDark,
        calendarYearBackground = primitive.primaryContainerDark,
        calendarSelectedBorder = primitive.primary,
        splashBackground = primitive.primary,
        splashCardBackground = primitive.splashCard
    )
}
