package com.hoabui.virtualbody3d.ui.theme.tokens.semantic

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import com.hoabui.virtualbody3d.ui.theme.tokens.primitive.PrimitiveColorTokens

/**
 * Semantic colors – wine-plum brand. Maps primitive tokens to UI meaning.
 * Legacy names (surfaceBorder, outlineSoft, dashboard*, etc.) kept for compatibility.
 */
@Immutable
data class SemanticColorTokens(
    val primary: Color,
    val primarySoft: Color,
    val onPrimaryContainer: Color,
    val background: Color,
    val surface: Color,
    val surfaceElevated: Color,
    val surfaceSubtle: Color,
    val borderSubtle: Color,
    val borderStrong: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val textPlaceholder: Color,
    val textBlack: Color,
    val error: Color,
    val onPrimary: Color,
    val onError: Color,
    val surfaceBorder: Color,
    val outlineSoft: Color,
    val surfaceOverlay: Color,
    val backgroundTransparent: Color,
    val backgroundScrim: Color,
    val previewTrack: Color,
    val primarySelected: Color,
    val dashboardPanelBackground: Color,
    val dashboardHandle: Color,
    val dashboardCalorieCardBackground: Color,
    val dashboardRingTrack: Color,
    val dashboardMealCardBackground: Color,
    val dashboardMealImageBackground: Color,
    val dashboardSummaryCardBackground: Color,
    val dashboardFloatingNavBackground: Color,
    val dashboardFloatingNavBorder: Color,
    val calorieDeficitPositive: Color,
    val calorieDeficitNegative: Color,
    val calorieRingTrack: Color,
    val calorieRingBackground: Color,
    val calorieIntake: Color,
    val calorieBurned: Color,
    val calendarYearBackground: Color,
    val calendarSelectedBorder: Color,
    val splashBackground: Color,
    val splashCardBackground: Color,
    val initialSetupProgressDotUnselected: Color,
    val initialSetupSkipText: Color,
    val initialSetupOptionBorder: Color,
    val initialSetupOptionSelectedBg: Color,
    val initialSetupStep4IconBg: Color,
    val initialSetupStep4IconBorder: Color,
    val initialSetupStep4DecorationBg: Color,
    val initialSetupOptionUnselectedIcon: Color,
    /** Difficulty badge: Beginner – text #16A34A */
    val difficultyBeginnerText: Color,
    /** Difficulty badge: Intermediate – text #D97706 */
    val difficultyIntermediateText: Color,
    /** Difficulty badge: Advanced – text #DC2626 */
    val difficultyAdvancedText: Color,
    /** Body region chip: Chest */
    val bodyRegionChest: Color,
    /** Body region chip: Back */
    val bodyRegionBack: Color,
    /** Body region chip: Shoulders */
    val bodyRegionShoulders: Color,
    /** Body region chip: Arms */
    val bodyRegionArms: Color,
    /** Body region chip: Core */
    val bodyRegionCore: Color,
    /** Body region chip: Legs */
    val bodyRegionLegs: Color
)

fun lightSemanticColors(primitive: PrimitiveColorTokens): SemanticColorTokens {
    return SemanticColorTokens(
        primary = primitive.primary,
        primarySoft = primitive.primaryContainerLight,
        onPrimaryContainer = primitive.onPrimaryContainerLight,
        background = primitive.backgroundLight,
        surface = primitive.surfaceLight,
        surfaceElevated = primitive.surfaceLight,
        surfaceSubtle = primitive.surfaceVariantLight,
        borderSubtle = primitive.borderSubtleLight,
        borderStrong = primitive.outlineLight,
        textPrimary = primitive.textPrimaryLight,
        textSecondary = primitive.textSecondaryLight,
        textMuted = primitive.textSecondaryLight,
        textPlaceholder = Color(0xFF757575),
        textBlack = Color(0xFF000000),
        error = primitive.error,
        onPrimary = primitive.onPrimary,
        onError = primitive.onPrimary,
        surfaceBorder = primitive.borderSubtleLight,
        outlineSoft = primitive.outlineLight,
        surfaceOverlay = primitive.surfaceLight,
        backgroundTransparent = primitive.transparent,
        backgroundScrim = primitive.backgroundDark,
        previewTrack = primitive.borderSubtleLight,
        primarySelected = primitive.primaryContainerLight,
        dashboardPanelBackground = primitive.surfaceLight,
        dashboardHandle = primitive.outlineLight,
        dashboardCalorieCardBackground = primitive.surfaceLight,
        dashboardRingTrack = primitive.outlineLight,
        dashboardMealCardBackground = primitive.surfaceLight,
        dashboardMealImageBackground = primitive.surfaceVariantLight,
        dashboardSummaryCardBackground = primitive.surfaceLight,
        dashboardFloatingNavBackground = primitive.surfaceLight,
        dashboardFloatingNavBorder = primitive.borderSubtleLight,
        calorieDeficitPositive = Color(0xFF16A34A),
        calorieDeficitNegative = Color(0xFFDC2626),
        calorieRingTrack = primitive.borderSubtleLight,
        calorieRingBackground = primitive.outlineLight,
        calorieIntake = Color(0xFF3B82F6),
        calorieBurned = Color(0xFFFF4D6D),
        calendarYearBackground = primitive.primaryContainerLight,
        calendarSelectedBorder = primitive.primary,
        splashBackground = primitive.primary,
        splashCardBackground = primitive.splashCard,
        initialSetupProgressDotUnselected = primitive.outlineLight,
        initialSetupSkipText = primitive.textSecondaryLight,
        initialSetupOptionBorder = primitive.outlineLight,
        initialSetupOptionSelectedBg = primitive.primaryContainerLight,
        initialSetupStep4IconBg = primitive.surfaceVariantLight,
        initialSetupStep4IconBorder = primitive.outlineLight,
        initialSetupStep4DecorationBg = primitive.surfaceVariantLight,
        initialSetupOptionUnselectedIcon = primitive.textSecondaryLight,
        difficultyBeginnerText = Color(0xFF16A34A),
        difficultyIntermediateText = Color(0xFFD97706),
        difficultyAdvancedText = Color(0xFFDC2626),
        bodyRegionChest = Color(0xFFDC2626),
        bodyRegionBack = Color(0xFF2563EB),
        bodyRegionShoulders = Color(0xFFEA580C),
        bodyRegionArms = Color(0xFF7C3AED),
        bodyRegionCore = Color(0xFF059669),
        bodyRegionLegs = Color(0xFF0D9488)
    )
}

fun darkSemanticColors(primitive: PrimitiveColorTokens): SemanticColorTokens {
    return SemanticColorTokens(
        primary = primitive.primary,
        primarySoft = primitive.primaryContainerDark,
        onPrimaryContainer = primitive.onPrimaryContainerDark,
        background = primitive.backgroundDark,
        surface = primitive.surfaceDark,
        surfaceElevated = primitive.surfaceDark,
        surfaceSubtle = primitive.surfaceVariantDark,
        borderSubtle = primitive.borderSubtleDark,
        borderStrong = primitive.outlineDark,
        textPrimary = primitive.textPrimaryDark,
        textSecondary = primitive.textSecondaryDark,
        textMuted = primitive.textSecondaryDark,
        textPlaceholder = Color(0xFFB0B0B0),
        textBlack = Color(0xFFFFFFFF),
        error = primitive.error,
        onPrimary = primitive.onPrimary,
        onError = primitive.onPrimary,
        surfaceBorder = primitive.borderSubtleDark,
        outlineSoft = primitive.outlineDark,
        surfaceOverlay = primitive.surfaceDark,
        backgroundTransparent = primitive.transparent,
        backgroundScrim = primitive.backgroundDark,
        previewTrack = primitive.outlineDark,
        primarySelected = primitive.primaryContainerDark,
        dashboardPanelBackground = primitive.surfaceDark,
        dashboardHandle = primitive.outlineDark,
        dashboardCalorieCardBackground = primitive.surfaceDark,
        dashboardRingTrack = primitive.outlineDark,
        dashboardMealCardBackground = primitive.surfaceDark,
        dashboardMealImageBackground = primitive.surfaceVariantDark,
        dashboardSummaryCardBackground = primitive.surfaceDark,
        dashboardFloatingNavBackground = primitive.surfaceDark,
        dashboardFloatingNavBorder = primitive.borderSubtleDark,
        calorieDeficitPositive = Color(0xFF16A34A),
        calorieDeficitNegative = Color(0xFFDC2626),
        calorieRingTrack = primitive.borderSubtleDark,
        calorieRingBackground = primitive.outlineDark,
        calorieIntake = Color(0xFF60A5FA),
        calorieBurned = Color(0xFFFF758F),
        calendarYearBackground = primitive.primaryContainerDark,
        calendarSelectedBorder = primitive.primary,
        splashBackground = primitive.primary,
        splashCardBackground = primitive.splashCard,
        initialSetupProgressDotUnselected = primitive.outlineDark,
        initialSetupSkipText = primitive.textSecondaryDark,
        initialSetupOptionBorder = primitive.outlineDark,
        initialSetupOptionSelectedBg = primitive.primaryContainerDark,
        initialSetupStep4IconBg = primitive.surfaceVariantDark,
        initialSetupStep4IconBorder = primitive.outlineDark,
        initialSetupStep4DecorationBg = primitive.surfaceVariantDark,
        initialSetupOptionUnselectedIcon = primitive.textSecondaryDark,
        difficultyBeginnerText = Color(0xFF16A34A),
        difficultyIntermediateText = Color(0xFFD97706),
        difficultyAdvancedText = Color(0xFFDC2626),
        bodyRegionChest = Color(0xFFDC2626),
        bodyRegionBack = Color(0xFF2563EB),
        bodyRegionShoulders = Color(0xFFEA580C),
        bodyRegionArms = Color(0xFF7C3AED),
        bodyRegionCore = Color(0xFF059669),
        bodyRegionLegs = Color(0xFF0D9488)
    )
}
