package com.hoabui.virtualbody3d.ui.theme.tokens.component

import androidx.compose.runtime.Immutable
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import com.hoabui.virtualbody3d.ui.theme.tokens.ElevationTokens
import com.hoabui.virtualbody3d.ui.theme.tokens.primitive.PrimitiveAlphaTokens
import com.hoabui.virtualbody3d.ui.theme.tokens.primitive.PrimitiveBorderTokens
import com.hoabui.virtualbody3d.ui.theme.tokens.primitive.PrimitiveSpacingTokens
import com.hoabui.virtualbody3d.ui.theme.tokens.semantic.gymBodyAnalysisLayoutSemantics

@Immutable
data class CardImageWithTextSizeTokens(
    val smallWidth: Dp,
    val smallHeight: Dp,
    val mediumWidth: Dp,
    val mediumHeight: Dp,
    val largeWidth: Dp,
    val largeHeight: Dp,
    val exerciseLibraryWidth: Dp,
    val exerciseLibraryHeight: Dp,
)

@Immutable
data class BodyAnalysisTokens(
    val topBarHorizontalPadding: Dp,
    val topBarVerticalPadding: Dp,
    val topBarInnerHorizontalPadding: Dp,
    val topBarBorderWidth: Dp,
    val topBarIconSize: Dp,
    val topBarActionElevation: Dp,
    val previewModelTopPadding: Dp,
    val scoreChipTopPadding: Dp,
    val metricChipFirstRowTopPadding: Dp,
    val metricChipSecondRowTopPadding: Dp,
    val metricChipSidePadding: Dp,
    val previewTrackBottomPadding: Dp,
    val previewTrackMaxWidth: Dp,
    val previewTrackHeight: Dp,
    val bottomBarBorderWidth: Dp,
    val bottomBarItemPadding: Dp,
    val bottomBarSelectedHorizontalPadding: Dp,
    val bottomBarSelectedVerticalPadding: Dp,
    val bottomBarLabelTopSpacing: Dp,
    val bottomBarIconContainerSize: Dp,
    val bottomBarIconSize: Dp,
    val bottomBarSelectionPillWidthExpanded: Dp,
    val bottomBarSelectionPillHeight: Dp,
    val dashboardPanelTopRadius: Dp,
    val dashboardPanelHorizontalPadding: Dp,
    val dashboardPanelTopPadding: Dp,
    val dashboardPanelBottomPadding: Dp,
    val dashboardPanelSectionSpacing: Dp,
    val dashboardHandleWidth: Dp,
    val dashboardHandleHeight: Dp,
    val dashboardGreetingIconSize: Dp,
    val dashboardGreetingIconContainerSize: Dp,
    val dashboardCalorieCardPadding: Dp,
    val dashboardCalorieRingSize: Dp,
    val dashboardCalorieRingOuterStrokeWidth: Dp,
    val dashboardCalorieRingInnerStrokeWidth: Dp,
    val dashboardCalorieRingGap: Dp,
    val dashboardMealItemWidth: Dp,
    val dashboardMealItemImageSize: Dp,
    val dashboardSummaryCardPadding: Dp,
    val dashboardSummaryCardHeight: Dp,
    val dashboardScrollContentBottomSpacing: Dp,
    val dashboardFloatingNavHorizontalPadding: Dp,
    val dashboardFloatingNavVerticalPadding: Dp,
    val dashboardFloatingNavBottomPadding: Dp,
    val metricChipMinWidth: Dp,
    val metricChipIconContainerSize: Dp,
    val metricChipIconSize: Dp,
    val scoreChipMinWidth: Dp,
    val scoreChipProminentMinWidth: Dp,
    val scoreChipProgressSize: Dp,
    val scoreChipProminentProgressSize: Dp,
    val scoreChipInnerSize: Dp,
    val scoreChipProminentInnerSize: Dp,
    val scoreChipStrokeWidth: Dp,
    val scoreChipProminentStrokeWidth: Dp,
    val bodyRegionItemWidth: Dp,
    val bodyRegionItemHeight: Dp,
    val cardImageWithText: CardImageWithTextSizeTokens,
    val gImageCardTextSectionTopPadding: Dp,
    val gImageCardCornerRadius: Dp,
    val upcomingExerciseChipWidth: Dp,
    val upcomingExerciseChipHeight: Dp,
    val upcomingExerciseChipImageSize: Dp,
    val upcomingExerciseChipImageCornerRadius: Dp,
    val upcomingExerciseChipContentHorizontalPadding: Dp,
    val bodyRegionPlaceholderSize: Dp,
    val dashboardCaloriePremiumRingSize: Dp,
    val dashboardCaloriePremiumRingStrokeWidth: Dp,
    val dashboardCaloriePremiumSideColumnWidth: Dp,
    val timelineItemWidth: Dp,
    val timelineItemSpacing: Dp,
    val timelineAvatarSquareSize: Dp,
    val timelineAvatarCornerRadius: Dp,
    val timelinePlaceholderIconSize: Dp,
    val timelineDotSize: Dp,
    val timelineLineThickness: Dp,
    val timelineLineOffsetY: Dp,
    val timelineDateSlotHeight: Dp,
    val timelineAvatarSelectedBorderWidth: Dp,
    val timelineRowSurfaceAlpha: Float,
    val timelineAvatarSelectedScale: Float,
    val timelineSecondaryMetricIconSize: Dp,
    val timelineUnselectedItemAlpha: Float,
    val timelinePagerSnapPositionalThreshold: Float,
    val heroSlimChipHeight: Dp,
    val heroSlimChipPaddingHorizontal: Dp,
    val heroSlimChipIconSize: Dp,
    val heroSlimChipIconTextGap: Dp,
    val heroSlimChipLabelLetterSpacing: TextUnit,
    val exerciseLibraryStickySearchHeaderMinHeight: Dp,
    /** Vertical gap between fixed search chrome and monthly summary card. */
    val exerciseLibrarySearchToSummaryGap: Dp,
    val exerciseLibraryMonthlySummaryCardHorizontalPadding: Dp,
    val exerciseLibraryMonthlySummaryCardVerticalPadding: Dp,
    val exerciseLibraryQuickAddIconContainerSize: Dp,
    val exerciseLibraryQuickAddTextInset: Dp,
    val exerciseLibrarySelectionBarTopCornerRadius: Dp,
    val exerciseLibraryCartNumericFieldWidth: Dp,
    val exerciseLibrarySelectionBarMinHeight: Dp,
    val exerciseLibrarySelectionBarAddButtonMaxWidth: Dp,
    val exerciseLibraryCartThumbnailSize: Dp,
    val exerciseLibraryAnchoredConsoleTopBorderWidth: Dp,
    val exerciseLibraryCartThumbnailActiveInset: Dp,
    val exerciseLibraryConsolePrecisionRowHeight: Dp,
    val exerciseLibraryWorkoutPlanFabSize: Dp,
    val exerciseLibraryWorkoutPlanFabIconSize: Dp,
    val exerciseLibraryWorkoutPlanFabBadgeMinSize: Dp,
    val exerciseLibraryCornerStickerDiameter: Dp,
    val exerciseLibraryCornerActionGlyphSize: Dp,
    val exerciseLibraryCornerStickerTouchTargetSize: Dp,
    val exerciseLibraryCartRemoveStickerVisualDiameter: Dp,
    val exerciseLibraryCartRemoveGlyphSize: Dp,
    val exerciseLibraryCartRemoveTouchTargetSize: Dp,
    val exerciseLibraryBookingSheetTopCornerRadius: Dp,
    val exerciseLibraryBookingDateChipMinWidth: Dp,
    val exerciseLibraryBookingDateChipHeight: Dp,
    val exerciseLibraryBookingTimeGridCellMinHeight: Dp,
    val exerciseLibraryBookingSectionIconSize: Dp,
    /** Fixed size for booking strip thumbnails (matches date chip height / 40dp scale); avoids LazyRow remeasure jitter. */
    val exerciseLibraryBookingStripThumbnailSize: Dp,
    /** Horizontal gap between strip thumbnail and title column ([BodyAnalysisLayoutSemantics.exerciseLibraryBookingStripImageTextGap]). */
    val exerciseLibraryBookingStripImageTextGap: Dp,
    /** Fixed width for each horizontal exercise snapshot card. */
    val exerciseLibraryBookingStripItemWidth: Dp,
    /** Max width for the trailing location selector label; ellipsis beyond this. */
    val exerciseLibraryBookingLocationSelectorMaxWidth: Dp,
    val exerciseLibraryBookingSheetMaxHeightFraction: Float,
    val exerciseLibraryBookingTimeSlotHorizontalMinWidth: Dp,
    val gImageCardSelectedSurfaceTintAlpha: Float,
    val gImageCardWeakSelectionSurfaceTintAlpha: Float,
)

fun gymBodyAnalysisTokens(
    spacing: PrimitiveSpacingTokens,
    border: PrimitiveBorderTokens,
    alpha: PrimitiveAlphaTokens,
    elevation: ElevationTokens,
): BodyAnalysisTokens {
    val layout = gymBodyAnalysisLayoutSemantics()
    return BodyAnalysisTokens(
        topBarHorizontalPadding = spacing.md,
        topBarVerticalPadding = layout.topBarVerticalPadding,
        topBarInnerHorizontalPadding = spacing.xxs,
        topBarBorderWidth = border.hairline,
        topBarIconSize = layout.topBarIconSize,
        topBarActionElevation = elevation.level3,
        previewModelTopPadding = spacing.xs,
        scoreChipTopPadding = layout.scoreChipTopPadding,
        metricChipFirstRowTopPadding = layout.metricChipFirstRowTopPadding,
        metricChipSecondRowTopPadding = layout.metricChipSecondRowTopPadding,
        metricChipSidePadding = spacing.md,
        previewTrackBottomPadding = spacing.xl,
        previewTrackMaxWidth = layout.previewTrackMaxWidth,
        previewTrackHeight = spacing.xs,
        bottomBarBorderWidth = border.hairline,
        bottomBarItemPadding = spacing.xxs,
        bottomBarSelectedHorizontalPadding = spacing.xs,
        bottomBarSelectedVerticalPadding = spacing.xxs,
        bottomBarLabelTopSpacing = spacing.xxs,
        bottomBarIconContainerSize = layout.bottomBarIconContainerSize,
        bottomBarIconSize = layout.bottomBarIconSize,
        bottomBarSelectionPillWidthExpanded = layout.bottomBarSelectionPillWidthExpanded,
        bottomBarSelectionPillHeight = layout.bottomBarSelectionPillHeight,
        dashboardPanelTopRadius = spacing.xl,
        dashboardPanelHorizontalPadding = spacing.md,
        dashboardPanelTopPadding = spacing.lg,
        dashboardPanelBottomPadding = spacing.xl,
        dashboardPanelSectionSpacing = spacing.lg,
        dashboardHandleWidth = layout.dashboardHandleWidth,
        dashboardHandleHeight = layout.dashboardHandleHeight,
        dashboardGreetingIconSize = layout.dashboardGreetingIconSize,
        dashboardGreetingIconContainerSize = layout.dashboardGreetingIconContainerSize,
        dashboardCalorieCardPadding = spacing.xs,
        dashboardCalorieRingSize = layout.dashboardCalorieRingSize,
        dashboardCalorieRingOuterStrokeWidth = spacing.xs,
        dashboardCalorieRingInnerStrokeWidth = spacing.xxxs,
        dashboardCalorieRingGap = spacing.xxs,
        dashboardMealItemWidth = layout.dashboardMealItemWidth,
        dashboardMealItemImageSize = layout.dashboardMealItemImageSize,
        dashboardSummaryCardPadding = spacing.md,
        dashboardSummaryCardHeight = layout.dashboardSummaryCardHeight,
        dashboardScrollContentBottomSpacing = layout.dashboardScrollContentBottomSpacing,
        dashboardFloatingNavHorizontalPadding = spacing.md,
        dashboardFloatingNavVerticalPadding = spacing.xs,
        dashboardFloatingNavBottomPadding = spacing.md,
        metricChipMinWidth = layout.metricChipMinWidth,
        metricChipIconContainerSize = layout.metricChipIconContainerSize,
        metricChipIconSize = layout.metricChipIconSize,
        scoreChipMinWidth = layout.scoreChipMinWidth,
        scoreChipProminentMinWidth = layout.scoreChipProminentMinWidth,
        scoreChipProgressSize = layout.scoreChipProgressSize,
        scoreChipProminentProgressSize = layout.scoreChipProminentProgressSize,
        scoreChipInnerSize = layout.scoreChipInnerSize,
        scoreChipProminentInnerSize = layout.scoreChipProminentInnerSize,
        scoreChipStrokeWidth = layout.scoreChipStrokeWidth,
        scoreChipProminentStrokeWidth = layout.scoreChipProminentStrokeWidth,
        bodyRegionItemWidth = layout.bodyRegionItemWidth,
        bodyRegionItemHeight = layout.bodyRegionItemHeight,
        cardImageWithText = CardImageWithTextSizeTokens(
            smallWidth = layout.cardSmallWidth,
            smallHeight = layout.cardSmallHeight,
            mediumWidth = layout.cardMediumWidth,
            mediumHeight = layout.cardMediumHeight,
            largeWidth = layout.cardLargeWidth,
            largeHeight = layout.cardLargeHeight,
            exerciseLibraryWidth = layout.cardExerciseLibraryWidth,
            exerciseLibraryHeight = layout.cardExerciseLibraryHeight,
        ),
        gImageCardTextSectionTopPadding = layout.gImageCardTextSectionTopPadding,
        gImageCardCornerRadius = layout.gImageCardCornerRadius,
        upcomingExerciseChipWidth = layout.upcomingExerciseChipWidth,
        upcomingExerciseChipHeight = layout.upcomingExerciseChipHeight,
        upcomingExerciseChipImageSize = layout.upcomingExerciseChipImageSize,
        upcomingExerciseChipImageCornerRadius = layout.upcomingExerciseChipImageCornerRadius,
        upcomingExerciseChipContentHorizontalPadding = layout.upcomingExerciseChipContentHorizontalPadding,
        bodyRegionPlaceholderSize = layout.bodyRegionPlaceholderSize,
        dashboardCaloriePremiumRingSize = layout.dashboardCaloriePremiumRingSize,
        dashboardCaloriePremiumRingStrokeWidth = spacing.md,
        dashboardCaloriePremiumSideColumnWidth = layout.dashboardCaloriePremiumSideColumnWidth,
        timelineItemWidth = layout.timelineItemWidth,
        timelineItemSpacing = spacing.md,
        timelineAvatarSquareSize = layout.timelineAvatarSquareSize,
        timelineAvatarCornerRadius = layout.timelineAvatarCornerRadius,
        timelinePlaceholderIconSize = spacing.xl,
        timelineDotSize = spacing.xs,
        timelineLineThickness = spacing.dividerThickness,
        timelineAvatarSelectedBorderWidth = border.thin,
        timelineRowSurfaceAlpha = alpha.TIMELINE_ROW_SURFACE,
        timelineAvatarSelectedScale = alpha.TIMELINE_AVATAR_SELECTED_SCALE,
        timelineSecondaryMetricIconSize = layout.timelineSecondaryMetricIconSize,
        timelineUnselectedItemAlpha = alpha.TIMELINE_UNSELECTED_ITEM,
        timelinePagerSnapPositionalThreshold = alpha.TIMELINE_PAGER_SNAP_POSITIONAL_THRESHOLD,
        timelineDateSlotHeight = spacing.md,
        timelineLineOffsetY = spacing.md + spacing.xxs + layout.timelineAvatarSquareSize + spacing.xxs + layout.timelineWeightLineEstimate + spacing.xxs + layout.timelineSecondaryBlockEstimate + spacing.xxs + spacing.xs / layout.timelineDotCenterDivisor,
        heroSlimChipHeight = layout.heroSlimChipHeight,
        heroSlimChipPaddingHorizontal = layout.heroSlimChipPaddingHorizontal,
        heroSlimChipIconSize = layout.heroSlimChipIconSize,
        heroSlimChipIconTextGap = layout.heroSlimChipIconTextGap,
        heroSlimChipLabelLetterSpacing = layout.heroSlimChipLabelLetterSpacing,
        exerciseLibraryStickySearchHeaderMinHeight = spacing.lg + spacing.md + spacing.xs + layout.heroSlimChipHeight + spacing.xxs,
        exerciseLibrarySearchToSummaryGap = spacing.sm,
        exerciseLibraryMonthlySummaryCardHorizontalPadding = spacing.md,
        exerciseLibraryMonthlySummaryCardVerticalPadding = spacing.sm,
        exerciseLibraryQuickAddIconContainerSize = layout.heroSlimChipHeight,
        exerciseLibraryQuickAddTextInset = spacing.xxl + spacing.xs,
        exerciseLibrarySelectionBarTopCornerRadius = layout.exerciseLibrarySelectionBarTopCornerRadius,
        exerciseLibraryCartNumericFieldWidth = layout.exerciseLibraryCartNumericFieldWidth,
        exerciseLibrarySelectionBarMinHeight = layout.exerciseLibraryCartThumbnailSize +
            layout.exerciseLibraryConsolePrecisionRowHeight * 2 +
            spacing.sm * 2 + spacing.md * 2,
        exerciseLibrarySelectionBarAddButtonMaxWidth = spacing.xl + spacing.xl + spacing.md,
        exerciseLibraryCartThumbnailSize = layout.exerciseLibraryCartThumbnailSize,
        exerciseLibraryAnchoredConsoleTopBorderWidth = layout.exerciseLibraryAnchoredConsoleTopBorderWidth,
        exerciseLibraryCartThumbnailActiveInset = layout.exerciseLibraryCartThumbnailActiveInset,
        exerciseLibraryConsolePrecisionRowHeight = layout.exerciseLibraryConsolePrecisionRowHeight,
        exerciseLibraryWorkoutPlanFabSize = layout.exerciseLibraryWorkoutPlanFabSize,
        exerciseLibraryWorkoutPlanFabIconSize = layout.exerciseLibraryWorkoutPlanFabIconSize,
        exerciseLibraryWorkoutPlanFabBadgeMinSize = layout.exerciseLibraryWorkoutPlanFabBadgeMinSize,
        exerciseLibraryCornerStickerDiameter = layout.exerciseLibraryCornerStickerDiameter,
        exerciseLibraryCornerActionGlyphSize = layout.exerciseLibraryCornerActionGlyphSize,
        exerciseLibraryCornerStickerTouchTargetSize = layout.exerciseLibraryCornerStickerTouchTargetSize,
        exerciseLibraryCartRemoveStickerVisualDiameter = layout.exerciseLibraryCartRemoveStickerVisualDiameter,
        exerciseLibraryCartRemoveGlyphSize = layout.exerciseLibraryCartRemoveGlyphSize,
        exerciseLibraryCartRemoveTouchTargetSize = layout.exerciseLibraryCartRemoveTouchTargetSize,
        exerciseLibraryBookingSheetTopCornerRadius = layout.exerciseLibraryBookingSheetTopCornerRadius,
        exerciseLibraryBookingDateChipMinWidth = layout.exerciseLibraryBookingDateChipMinWidth,
        exerciseLibraryBookingDateChipHeight = layout.exerciseLibraryBookingDateChipHeight,
        exerciseLibraryBookingTimeGridCellMinHeight = layout.exerciseLibraryBookingTimeGridCellMinHeight,
        exerciseLibraryBookingSectionIconSize = layout.exerciseLibraryBookingSectionIconSize,
        exerciseLibraryBookingStripThumbnailSize = layout.exerciseLibraryBookingDateChipHeight,
        exerciseLibraryBookingStripImageTextGap = layout.exerciseLibraryBookingStripImageTextGap,
        exerciseLibraryBookingStripItemWidth = layout.exerciseLibraryBookingStripItemWidth,
        exerciseLibraryBookingLocationSelectorMaxWidth = layout.exerciseLibraryBookingLocationSelectorMaxWidth,
        exerciseLibraryBookingSheetMaxHeightFraction = layout.exerciseLibraryBookingSheetMaxHeightFraction,
        exerciseLibraryBookingTimeSlotHorizontalMinWidth = layout.exerciseLibraryBookingTimeSlotHorizontalMinWidth,
        gImageCardSelectedSurfaceTintAlpha = alpha.IMAGE_CARD_SELECTED_TINT,
        gImageCardWeakSelectionSurfaceTintAlpha = alpha.IMAGE_CARD_WEAK_SELECTION_TINT,
    )
}
